### ISSUE TITLE
Link to the old website points to the new website

### ISSUE THREAD

**Issue by ilankri** [ocsigen/ocsigen.org-deprecated#30]
![screenshot_2018-04-20_17-44-40](https://user-images.githubusercontent.com/32814460/39060768-92b4d7cc-44c2-11e8-92db-719de358ac3a.png)

I imagine that this link on the home page is supposed to point to the old website of Ocsigen.

**Comment by balat** [comment]
Thanks! 
Actually it was removed but came back for some reason ...
