### ISSUE TITLE
Page not found on http://ocsigen.org/ocsimore/

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen.org-deprecated#40]
+ check other projects

**Comment by ulugbekna** [comment]
There are several pages that are not found either: 
https://ocsigen.org/tuto/latest/manual/tutowidgets
https://ocsigen.org/tuto/latest/manual/application
https://ocsigen.org/tuto/latest/manual/interaction
https://ocsigen.org/install
http://ocsigen.org/logs/

**Comment by leovalais** [comment]
@ulugbekna thanks for reporting. Can you please tell me which page links you to http://ocsigen.org/logs/ ?

**Comment by ulugbekna** [comment]
@leovalais I can't really remember, but it wasn't in the docs. It was in the cmd installation or something.

**Comment by leovalais** [comment]
We can't find where that link could be... If you find it again somewhere, please let us know.
