### ISSUE TITLE
js_of_ocaml manual examples missing (404)

### ISSUE THREAD

**Issue by stevebleazard** [ocsigen/ocsigen.org-deprecated#41]
The examples seem to be missing from the js_of_ocaml manual:

https://ocsigen.org/js_of_ocaml/3.1.0/manual/files/toplevel/index.html
https://ocsigen.org/js_of_ocaml/3.1.0/manual/files/graph_viewer/index.html

**Comment by balat** [comment]
@leovalais could you have a look at this soon?

**Comment by leovalais** [comment]
@hhugo the examples' HTML files disappear after version 2.8.4 and the necessary JS files only exist inside `ocsigen.org-data`.
Should I include them into current version's docs or remove the links from the menu?

**Comment by balat** [comment]
Solved. Create new  issue if you observe a problem.
